/* Scenario data.
 *
 * Every "true" value here is an approximation good to well inside the grading
 * bands (the app scores order-of-magnitude accuracy, so a 10% error in a source
 * figure never changes a grade). City figures are administrative core-municipality
 * unless `basis` says otherwise — which is itself the planted ambiguity the real
 * exercise tests, so the basis is always shown to you.
 */
const Data = (function () {

  /* ---------------- cities: lat, lon, population, area km2 ---------------- */
  const CITIES = [
    { name: 'London',        lat: 51.5074, lon: -0.1278,   pop: 8.90e6,  area: 1572,  basis: 'Greater London' },
    { name: 'Paris',         lat: 48.8566, lon: 2.3522,    pop: 2.10e6,  area: 105,   basis: 'city proper' },
    { name: 'Amsterdam',     lat: 52.3676, lon: 4.9041,    pop: 0.93e6,  area: 219,   basis: 'municipality' },
    { name: 'Berlin',        lat: 52.5200, lon: 13.4050,   pop: 3.80e6,  area: 891,   basis: 'city state' },
    { name: 'Madrid',        lat: 40.4168, lon: -3.7038,   pop: 3.30e6,  area: 604,   basis: 'city proper' },
    { name: 'Barcelona',     lat: 41.3874, lon: 2.1686,    pop: 1.66e6,  area: 101,   basis: 'city proper' },
    { name: 'Rome',          lat: 41.9028, lon: 12.4964,   pop: 2.75e6,  area: 1285,  basis: 'comune' },
    { name: 'Milan',         lat: 45.4642, lon: 9.1900,    pop: 1.37e6,  area: 182,   basis: 'comune' },
    { name: 'Vienna',        lat: 48.2082, lon: 16.3738,   pop: 2.00e6,  area: 415,   basis: 'city state' },
    { name: 'Dublin',        lat: 53.3498, lon: -6.2603,   pop: 0.59e6,  area: 115,   basis: 'city council' },
    { name: 'Copenhagen',    lat: 55.6761, lon: 12.5683,   pop: 0.66e6,  area: 90,    basis: 'municipality' },
    { name: 'Stockholm',     lat: 59.3293, lon: 18.0686,   pop: 1.00e6,  area: 188,   basis: 'municipality' },
    { name: 'Lisbon',        lat: 38.7223, lon: -9.1393,   pop: 0.55e6,  area: 100,   basis: 'city proper' },
    { name: 'Warsaw',        lat: 52.2297, lon: 21.0122,   pop: 1.86e6,  area: 517,   basis: 'city proper' },
    { name: 'Prague',        lat: 50.0755, lon: 14.4378,   pop: 1.38e6,  area: 496,   basis: 'city proper' },
    { name: 'Brussels',      lat: 50.8503, lon: 4.3517,    pop: 1.22e6,  area: 162,   basis: 'Capital Region' },
    { name: 'Munich',        lat: 48.1351, lon: 11.5820,   pop: 1.51e6,  area: 310,   basis: 'city proper' },
    { name: 'Hamburg',       lat: 53.5511, lon: 9.9937,    pop: 1.90e6,  area: 755,   basis: 'city state' },
    { name: 'Zurich',        lat: 47.3769, lon: 8.5417,    pop: 0.44e6,  area: 88,    basis: 'city proper' },
    { name: 'Athens',        lat: 37.9838, lon: 23.7275,   pop: 0.64e6,  area: 39,    basis: 'municipality' },
    { name: 'New York City', lat: 40.7128, lon: -74.0060,  pop: 8.30e6,  area: 778,   basis: 'five boroughs, land' },
    { name: 'Chicago',       lat: 41.8781, lon: -87.6298,  pop: 2.66e6,  area: 606,   basis: 'city proper, land' },
    { name: 'San Francisco', lat: 37.7749, lon: -122.4194, pop: 0.81e6,  area: 121,   basis: 'city proper, land' },
    { name: 'Toronto',       lat: 43.6532, lon: -79.3832,  pop: 2.79e6,  area: 631,   basis: 'city proper' },
    { name: 'Mexico City',   lat: 19.4326, lon: -99.1332,  pop: 9.20e6,  area: 1495,  basis: 'Federal District' },
    { name: 'Sao Paulo',     lat: -23.5505, lon: -46.6333, pop: 11.50e6, area: 1521,  basis: 'municipality' },
    { name: 'Tokyo',         lat: 35.6762, lon: 139.6503,  pop: 9.70e6,  area: 628,   basis: '23 special wards' },
    { name: 'Singapore',     lat: 1.3521,  lon: 103.8198,  pop: 5.90e6,  area: 734,   basis: 'whole country' },
    { name: 'Hong Kong',     lat: 22.3193, lon: 114.1694,  pop: 7.50e6,  area: 1114,  basis: 'whole territory' },
    { name: 'Mumbai',        lat: 19.0760, lon: 72.8777,   pop: 12.50e6, area: 603,   basis: 'city proper' },
  ];

  const R_EARTH = 6371;
  function greatCircle(a, b) {
    const rad = Math.PI / 180;
    const la = a.lat * rad, lb = b.lat * rad, dl = (b.lon - a.lon) * rad;
    const c = Math.sin(la) * Math.sin(lb) + Math.cos(la) * Math.cos(lb) * Math.cos(dl);
    return R_EARTH * Math.acos(Math.min(1, Math.max(-1, c)));
  }
  const density = c => c.pop / c.area;

  /* ---------------- Fermi bank ----------------
   * hint: the decomposition a trader would say out loud, shown only in the debrief.
   */
  const FERMI = [
    { q: 'Stations on the London Underground', v: 272, unit: 'stations', hint: '11 lines, roughly 25 stations each.' },
    { q: 'Passenger journeys on the London Underground in a year', v: 1.18e9, unit: 'journeys', hint: '~4M a weekday x ~300 equivalent days.' },
    { q: 'Passengers through Heathrow in a year', v: 83e6, unit: 'passengers', hint: '~1,300 flights a day x ~180 seats x 0.85 load x 365, both directions.' },
    { q: 'Passengers through Amsterdam Schiphol in a year', v: 67e6, unit: 'passengers', hint: 'Europe’s third busiest, a little under Heathrow.' },
    { q: 'Eurostar passengers in a year', v: 19e6, unit: 'passengers', hint: '~50 trains a day x ~750 seats x 0.7 x 365.' },
    { q: 'Commercial flights worldwide in a day', v: 100e3, unit: 'flights', hint: '~25,000 commercial aircraft, ~4 sectors a day each.' },
    { q: 'Commercial aircraft airborne at a typical moment', v: 10e3, unit: 'aircraft', hint: '100k flights a day, ~2.5h each, so ~10k in the air on average.' },
    { q: 'McDonald’s restaurants worldwide', v: 43e3, unit: 'restaurants', hint: '~13,500 in the US, which is roughly a third.' },
    { q: 'Starbucks stores worldwide', v: 40e3, unit: 'stores', hint: 'Similar order to McDonald’s, more concentrated in the US and China.' },
    { q: 'Licensed pubs in the United Kingdom', v: 45e3, unit: 'pubs', hint: '67M people, roughly one pub per 1,500 people.' },
    { q: 'Bicycles in the Netherlands', v: 23e6, unit: 'bicycles', hint: '17.9M people, more than one bike each.' },
    { q: 'Licensed vehicles in the United Kingdom', v: 41e6, unit: 'vehicles', hint: '~33M cars plus vans, bikes and lorries.' },
    { q: 'Yellow medallion taxis in New York City', v: 13587, unit: 'taxis', hint: 'The medallion count is fixed by law near 13,600.' },
    { q: 'Licensed black cabs in London', v: 15e3, unit: 'cabs', hint: 'Roughly the same order as New York medallions.' },
    { q: 'Goals scored in a full Premier League season', v: 1080, unit: 'goals', hint: '380 matches x ~2.85 goals a match.' },
    { q: 'Seconds in a year', v: 31.56e6, unit: 'seconds', hint: 'pi times ten million is the classic mnemonic.' },
    { q: 'Heartbeats in an 80-year human life', v: 2.5e9, unit: 'beats', hint: '~70 a minute x 42M minutes.' },
    { q: 'Cells in the human body', v: 3.7e13, unit: 'cells', hint: 'Roughly the same order as the bacteria living on you.' },
    { q: 'Hairs on a human head', v: 100e3, unit: 'hairs', hint: '~600cm2 of scalp at ~170 per cm2.' },
    { q: 'Total length of blood vessels in one adult', v: 100e3, unit: 'km', hint: 'Twice around the Earth, mostly capillaries.' },
    { q: 'Distance from the Earth to the Moon', v: 384400, unit: 'km', hint: '~30 Earth diameters; light takes 1.3 seconds.' },
    { q: 'Mass of the Earth', v: 5.97e24, unit: 'kg', hint: 'Volume ~1.08e21 m3 at a mean density of 5,500 kg/m3.' },
    { q: 'Stars in the Milky Way', v: 2e11, unit: 'stars', hint: 'Usually quoted as 100 to 400 billion.' },
    { q: 'Trees on Earth', v: 3e12, unit: 'trees', hint: 'About 400 per living person.' },
    { q: 'People alive on Earth', v: 8.2e9, unit: 'people', hint: 'Know this one exactly.' },
    { q: 'Babies born worldwide in a day', v: 385e3, unit: 'births', hint: '8.2bn people, ~72 year life, so ~140M births a year.' },
    { q: 'Deaths worldwide in a day', v: 170e3, unit: 'deaths', hint: '~62M a year, well below births.' },
    { q: 'Google searches in a day', v: 8.5e9, unit: 'searches', hint: '~5bn internet users, a couple of searches each.' },
    { q: 'iPhones sold in a year', v: 230e6, unit: 'phones', hint: '~1.4bn active iPhones on a ~5 year replacement cycle.' },
    { q: 'Netflix paid subscriptions worldwide', v: 300e6, unit: 'subscriptions', hint: 'Roughly one household in eight outside China.' },
    { q: 'Spotify monthly active users', v: 675e6, unit: 'users', hint: 'Around twice Netflix, because the free tier counts.' },
    { q: 'WhatsApp monthly active users', v: 2.7e9, unit: 'users', hint: 'A third of everyone alive.' },
    { q: 'Amazon employees worldwide', v: 1.55e6, unit: 'employees', hint: 'Second largest private employer after Walmart.' },
    { q: 'People employed by the NHS across the UK', v: 1.7e6, unit: 'employees', hint: 'Roughly one in forty UK workers.' },
    { q: 'Students at UK universities', v: 2.9e6, unit: 'students', hint: '~700k a year across ~3.5 years of study.' },
    { q: 'Barrels of oil consumed worldwide in a day', v: 103e6, unit: 'barrels', hint: '~12 barrels per person per year.' },
    { q: 'Global CO2 emissions from fossil fuels in a year', v: 37e9, unit: 'tonnes', hint: '~4.5 tonnes per person.' },
    { q: 'Container ships in the world fleet', v: 6e3, unit: 'ships', hint: 'Carrying ~26M TEU of capacity between them.' },
    { q: 'ATMs worldwide', v: 3e6, unit: 'machines', hint: 'Falling, roughly one per 2,700 people.' },
    { q: 'Bank of England notes in circulation', v: 4.6e9, unit: 'notes', hint: '~GBP 80bn in value at an average note near GBP 17.' },
    { q: 'Height of the Eiffel Tower', v: 330, unit: 'metres', hint: 'About a 100-storey building.' },
    { q: 'Mass of the Eiffel Tower', v: 10100, unit: 'tonnes', hint: '7,300 tonnes of iron plus foundations.' },
    { q: 'Height of the Burj Khalifa', v: 828, unit: 'metres', hint: 'Two and a half Eiffel Towers.' },
    { q: 'Bricks in the Empire State Building', v: 10e6, unit: 'bricks', hint: 'Facade area over brick area, roughly.' },
    { q: 'Length of the M25 motorway', v: 188, unit: 'km', hint: 'A circle of radius ~30km around London.' },
    { q: 'Member states of the United Nations', v: 193, unit: 'states', hint: 'Know this one exactly.' },
    { q: 'Islands in Indonesia', v: 17500, unit: 'islands', hint: 'Officially 17,504 by the latest survey.' },
    { q: 'Lego bricks produced in a year', v: 110e9, unit: 'bricks', hint: '~14 per person alive, per year.' },
    { q: 'Distinct chess games possible after two moves each', v: 197281, unit: 'games', hint: '20 x 20 first moves, then ~440 replies on average.' },
    { q: 'Ways to shuffle a standard 52-card deck', v: 8.07e67, unit: 'orderings', hint: '52 factorial. log10 is about 67.9.' },
    { q: 'Water in an Olympic swimming pool', v: 2500, unit: 'cubic metres', hint: '50 x 25 x 2 metres.' },
    { q: 'Grains of rice in a one-kilogram bag', v: 50e3, unit: 'grains', hint: 'A grain weighs about 20mg.' },
    { q: 'Atoms in a single grain of sand', v: 6e19, unit: 'atoms', hint: '~0.7mg of SiO2 over a molar mass of 60.' },
    { q: 'Cups of coffee drunk worldwide in a day', v: 2.25e9, unit: 'cups', hint: 'Around one cup per four people alive.' },
    { q: 'Pizzas sold in the United States in a year', v: 3e9, unit: 'pizzas', hint: '~9 per American per year.' },
    { q: 'Takeoff weight of a fully loaded Boeing 747', v: 400, unit: 'tonnes', hint: '~180t empty, ~180t fuel, ~40t payload.' },
    { q: 'Flights handled by Heathrow in a day', v: 1300, unit: 'flights', hint: 'Two runways at near-capacity, ~45 movements an hour each.' },
    { q: 'Postcodes in the United Kingdom', v: 1.8e6, unit: 'postcodes', hint: '~29M addresses at ~15 addresses per postcode.' },
    { q: 'Trains in service on the London Underground at the morning peak', v: 540, unit: 'trains', hint: '11 lines, ~50 trains each at peak.' },
    { q: 'Weight of all the ants on Earth', v: 12e9, unit: 'kg', hint: '~20 quadrillion ants at a few milligrams each.' },
    /* ---- added 15 Sep 2026: the wider Fermi bank ---- */
    /* Netherlands and Amsterdam */
    { q: 'Population of the Netherlands', v: 18.0e6, unit: 'people', hint: 'Know this exactly for an Amsterdam interview.' },
    { q: 'Population of Amsterdam, the municipality', v: 930e3, unit: 'people', hint: 'Metro area is ~2.5M; say which.' },
    { q: 'Area of the Netherlands', v: 41.5e3, unit: 'km2', hint: 'Roughly 300 x 140 km; a third below sea level.' },
    { q: 'Population density of the Netherlands', v: 520, unit: 'per km2', hint: '18M over 41,500 km2 (land only is ~530).' },
    { q: 'Canals in Amsterdam', v: 165, unit: 'canals', hint: 'About 100 km of waterway and 1,500 bridges.' },
    { q: 'Bridges in Amsterdam', v: 1500, unit: 'bridges', hint: '165 canals, roughly nine crossings each.' },
    { q: 'Overnight tourists visiting Amsterdam in a year', v: 20e6, unit: 'visitors', hint: 'More than twenty per resident.' },
    { q: 'Municipalities in the Netherlands', v: 342, unit: 'municipalities', hint: 'Falling through mergers; 12 provinces.' },
    { q: 'Cargo through the Port of Rotterdam in a year', v: 440e6, unit: 'tonnes', hint: 'Europe’s largest port by a distance.' },
    { q: 'Windmills still standing in the Netherlands', v: 1200, unit: 'windmills', hint: 'Historic ones; wind turbines are separate and number ~3,000 onshore.' },
    { q: 'Tulip bulbs exported from the Netherlands in a year', v: 2e9, unit: 'bulbs', hint: 'Roughly 250 per Dutch resident.' },
    { q: 'Cars registered in the Netherlands', v: 9.3e6, unit: 'cars', hint: 'About one per two people, low for Europe because of the bikes.' },
    { q: 'Length of the Dutch cycle-path network', v: 37e3, unit: 'km', hint: 'Nearly the Earth’s circumference in dedicated paths.' },
    { q: 'Kilometres of dykes protecting the Netherlands', v: 17.5e3, unit: 'km', hint: 'Primary and regional flood defences together.' },
    { q: 'Passengers on the Dutch railways (NS) in a day', v: 1.1e6, unit: 'journeys', hint: '~400M a year, most of them commuters.' },
    { q: 'Students at Dutch universities', v: 340e3, unit: 'students', hint: 'Research universities only; add ~500k at applied universities.' },
    { q: 'Employees at IMC worldwide', v: 1500, unit: 'employees', hint: 'Across Amsterdam, Chicago, Sydney, Mumbai and smaller offices.' },
    { q: 'Employees at Optiver worldwide', v: 2000, unit: 'employees', hint: 'Similar scale to IMC, Amsterdam-headquartered.' },
    { q: 'Employees at Flow Traders worldwide', v: 700, unit: 'employees', hint: 'The smallest of the three Amsterdam market makers.' },
    { q: 'Companies listed on Euronext Amsterdam', v: 130, unit: 'companies', hint: 'The AEX index holds 25 of them.' },

    /* Europe and the UK */
    { q: 'Population of the European Union', v: 450e6, unit: 'people', hint: '27 members; Germany is the largest at 84M.' },
    { q: 'Population of London', v: 8.9e6, unit: 'people', hint: 'Greater London; the metro area is ~14M.' },
    { q: 'Population of Paris, city proper', v: 2.1e6, unit: 'people', hint: 'The metro area is ~12M; always say which.' },
    { q: 'Population of Germany', v: 84e6, unit: 'people', hint: 'The EU’s largest by 15M.' },
    { q: 'Countries in the world', v: 195, unit: 'countries', hint: '193 UN members plus two observers.' },
    { q: 'Countries in Africa', v: 54, unit: 'countries', hint: 'Just over a quarter of all countries.' },
    { q: 'Countries using the euro', v: 21, unit: 'countries', hint: 'Bulgaria joined in January 2026, Croatia in 2023.' },
    { q: 'Members of NATO', v: 32, unit: 'members', hint: 'Finland and Sweden brought it from 30.' },
    { q: 'Length of the coastline of Great Britain', v: 17.8e3, unit: 'km', hint: 'Depends on the ruler; this is the OS figure.' },
    { q: 'Length of the River Thames', v: 346, unit: 'km', hint: 'Source in Gloucestershire to the estuary.' },
    { q: 'Length of the River Rhine', v: 1230, unit: 'km', hint: 'Swiss Alps to Rotterdam.' },
    { q: 'Length of the Danube', v: 2850, unit: 'km', hint: 'Black Forest to the Black Sea, ten countries.' },
    { q: 'Height of Mont Blanc', v: 4808, unit: 'metres', hint: 'Western Europe’s highest; Everest is 8,849.' },
    { q: 'Height of Ben Nevis', v: 1345, unit: 'metres', hint: 'Britain’s highest, about a quarter of Mont Blanc.' },
    { q: 'Length of the Channel Tunnel', v: 50, unit: 'km', hint: '38 km of it under the sea.' },
    { q: 'Length of the UK motorway network', v: 3800, unit: 'km', hint: 'Small: the whole road network is ~400,000 km.' },
    { q: 'Length of the German Autobahn network', v: 13.2e3, unit: 'km', hint: 'Three and a half times the UK motorways.' },
    { q: 'Passengers through Paris Charles de Gaulle in a year', v: 70e6, unit: 'passengers', hint: 'Neck and neck with Schiphol.' },
    { q: 'Passengers through Frankfurt Airport in a year', v: 62e6, unit: 'passengers', hint: 'Germany’s largest hub.' },
    { q: 'Passengers through Istanbul Airport in a year', v: 80e6, unit: 'passengers', hint: 'Now Europe’s busiest, edging Heathrow.' },
    { q: 'Passengers on the Paris Metro in a year', v: 1.5e9, unit: 'journeys', hint: 'A little above the London Underground.' },
    { q: 'Stations on the Paris Metro', v: 308, unit: 'stations', hint: 'Sixteen lines, denser than London.' },
    { q: 'Seats in Wembley Stadium', v: 90e3, unit: 'seats', hint: 'The largest in the UK; Camp Nou is ~99k.' },
    { q: 'Seats at the Johan Cruyff Arena', v: 56e3, unit: 'seats', hint: 'Ajax’s ground, Amsterdam.' },
    { q: 'Total attendance across a Premier League season', v: 15e6, unit: 'spectators', hint: '380 matches at ~40,000.' },
    { q: 'Professional footballers in England’s top four divisions', v: 2e3, unit: 'players', hint: '92 clubs at ~22 first-team players.' },
    { q: 'Rooms in Buckingham Palace', v: 775, unit: 'rooms', hint: 'Including 78 bathrooms.' },
    { q: 'Books in the British Library', v: 14e6, unit: 'books', hint: '170M items in total counting maps, journals and manuscripts.' },
    { q: 'Words in the complete works of Shakespeare', v: 885e3, unit: 'words', hint: '37 plays at ~22,000 plus the poems.' },
    { q: 'Words in the English language (OED headwords)', v: 600e3, unit: 'words', hint: 'A fluent adult knows 20-35k of them.' },
    { q: 'Piano tuners in Chicago', v: 100, unit: 'tuners', hint: 'The original Fermi question: 2.7M people, one piano per 20 households, tuned yearly, four a day.' },
    { q: 'Piano tuners in London', v: 300, unit: 'tuners', hint: 'Scale the Chicago answer by population.' },

    /* World scale */
    { q: 'Land area of the Earth', v: 149e6, unit: 'km2', hint: '29% of 510M km2 total surface.' },
    { q: 'Circumference of the Earth', v: 40e3, unit: 'km', hint: 'The metre was defined so this is 40,000 km.' },
    { q: 'Surface area of the oceans', v: 361e6, unit: 'km2', hint: '71% of the surface.' },
    { q: 'Volume of water in the oceans', v: 1.35e9, unit: 'km3', hint: 'Average depth 3.7 km over 361M km2.' },
    { q: 'Average depth of the ocean', v: 3700, unit: 'metres', hint: 'Deepest point ~11,000 m.' },
    { q: 'Height of Mount Everest', v: 8849, unit: 'metres', hint: 'Passenger jets cruise at 10-12 km.' },
    { q: 'Age of the Earth', v: 4.54e9, unit: 'years', hint: 'The universe is 13.8bn.' },
    { q: 'Age of the universe', v: 13.8e9, unit: 'years', hint: 'Three times the age of the Earth.' },
    { q: 'Distance from the Earth to the Sun', v: 150e6, unit: 'km', hint: 'One astronomical unit; light takes 8 minutes.' },
    { q: 'Diameter of the Sun', v: 1.39e6, unit: 'km', hint: '109 Earth diameters.' },
    { q: 'Speed of light', v: 3.0e8, unit: 'm/s', hint: 'Seven and a half times round the Earth per second.' },
    { q: 'Speed of sound in air', v: 340, unit: 'm/s', hint: 'A kilometre every three seconds; count after the lightning.' },
    { q: 'Cruising speed of a passenger jet', v: 900, unit: 'km/h', hint: 'About 250 m/s, Mach 0.85.' },
    { q: 'Countries with a population above 100 million', v: 16, unit: 'countries', hint: 'India, China, US, Indonesia, Pakistan, Nigeria, Brazil, Bangladesh, Russia, Mexico, Ethiopia, Japan, Philippines, Egypt, DR Congo, Vietnam.' },
    { q: 'Population of India', v: 1.44e9, unit: 'people', hint: 'Overtook China in 2023.' },
    { q: 'Population of China', v: 1.41e9, unit: 'people', hint: 'Now falling by a million or two a year.' },
    { q: 'Population of the United States', v: 340e6, unit: 'people', hint: 'Third largest, less than a quarter of India.' },
    { q: 'Population of Africa', v: 1.5e9, unit: 'people', hint: 'Growing fastest; Nigeria alone is 230M.' },
    { q: 'Population of Nigeria', v: 230e6, unit: 'people', hint: 'Africa’s largest; heading for 400M by 2050.' },
    { q: 'Population of Tokyo, the metro area', v: 37e6, unit: 'people', hint: 'The world’s largest urban area; the 23 wards are 9.7M.' },
    { q: 'Population of New York City', v: 8.3e6, unit: 'people', hint: 'Five boroughs; the metro area is ~20M.' },
    { q: 'Population of Australia', v: 27e6, unit: 'people', hint: 'Fewer than the Netherlands plus Belgium, on a continent.' },
    { q: 'Population of Chicago, city proper', v: 2.7e6, unit: 'people', hint: 'Metro area ~9.5M.' },
    { q: 'Population of Sydney', v: 5.3e6, unit: 'people', hint: 'A fifth of all Australians.' },
    { q: 'Cities with more than one million people', v: 550, unit: 'cities', hint: 'Roughly 40% of humanity lives in one.' },
    { q: 'Cities with more than ten million people', v: 35, unit: 'cities', hint: 'The megacities; over half are in Asia.' },
    { q: 'People living in cities worldwide', v: 4.6e9, unit: 'people', hint: 'Passed half of humanity around 2007; now ~57%.' },
    { q: 'Native English speakers worldwide', v: 400e6, unit: 'people', hint: 'Total speakers including second language ~1.5bn.' },
    { q: 'Languages spoken in the world', v: 7000, unit: 'languages', hint: 'Half of them have under 10,000 speakers.' },
    { q: 'Species of bird', v: 11e3, unit: 'species', hint: 'Mammals are ~6,500; insects run into the millions.' },
    { q: 'Domestic cats in the world', v: 600e6, unit: 'cats', hint: 'One per 14 people; dogs are ~900M.' },
    { q: 'Domestic dogs in the world', v: 900e6, unit: 'dogs', hint: 'Roughly one per nine people.' },
    { q: 'Cattle in the world', v: 1.5e9, unit: 'cattle', hint: 'Nearly one per five people; India and Brazil lead.' },
    { q: 'Chickens alive in the world at any moment', v: 26e9, unit: 'chickens', hint: 'Three per person; ~75bn slaughtered a year.' },
    { q: 'Sheep in New Zealand', v: 24e6, unit: 'sheep', hint: 'Under five per person now, down from 22 in 1982.' },
    { q: 'Wild elephants in Africa', v: 415e3, unit: 'elephants', hint: 'Down from ~1.3M in 1979.' },
    { q: 'Honeybees in a single hive in summer', v: 50e3, unit: 'bees', hint: 'One queen, tens of thousands of workers.' },

    /* Energy, transport, industry */
    { q: 'Cars in the world', v: 1.5e9, unit: 'cars', hint: 'Roughly one per five people; ~1.2bn passenger cars plus light trucks.' },
    { q: 'New cars sold worldwide in a year', v: 75e6, unit: 'cars', hint: 'Fleet of ~1.5bn on a ~20 year life.' },
    { q: 'Electric cars sold worldwide in a year', v: 17e6, unit: 'cars', hint: 'About a fifth of new sales; over half of them in China.' },
    { q: 'Tesla cars delivered in a year', v: 1.8e6, unit: 'cars', hint: 'Roughly 2.4% of global car sales.' },
    { q: 'Toyota cars sold in a year', v: 11e6, unit: 'cars', hint: 'The largest carmaker, ~14% of the market.' },
    { q: 'Boeing 747s ever built', v: 1574, unit: 'aircraft', hint: 'Production ended in 2023 after 54 years.' },
    { q: 'Commercial aircraft in service worldwide', v: 28e3, unit: 'aircraft', hint: 'Airbus and Boeing each deliver ~600-800 a year.' },
    { q: 'Passengers carried by airlines worldwide in a year', v: 4.7e9, unit: 'passengers', hint: 'More than half a flight per person alive.' },
    { q: 'Shipping containers (TEU) moved through ports in a year', v: 850e6, unit: 'TEU', hint: 'Each box is counted at every port it touches.' },
    { q: 'Ships in the world merchant fleet', v: 105e3, unit: 'ships', hint: 'Over 100 gross tonnes; ~6,000 are container ships.' },
    { q: 'Cars crossing London’s Tower Bridge in a day', v: 40e3, unit: 'vehicles', hint: 'A busy two-lane crossing.' },
    { q: 'Passengers on Amsterdam Centraal in a day', v: 200e3, unit: 'passengers', hint: 'The busiest station in the Netherlands.' },
    { q: 'Electricity used by the world in a year', v: 30e12, unit: 'kWh', hint: '~3,700 kWh per person; the UK uses ~4,500, the US ~12,000.' },
    { q: 'Electricity used by a UK household in a year', v: 2700, unit: 'kWh', hint: 'Plus ~11,500 kWh of gas.' },
    { q: 'Power output of a large nuclear reactor', v: 1000, unit: 'MW', hint: 'One gigawatt, enough for ~1M European homes.' },
    { q: 'Nuclear reactors operating worldwide', v: 415, unit: 'reactors', hint: 'About 10% of world electricity.' },
    { q: 'Wind turbines installed worldwide', v: 400e3, unit: 'turbines', hint: '~1,000 GW at ~2.5 MW each.' },
    { q: 'Energy in a barrel of oil', v: 1700, unit: 'kWh', hint: '159 litres; a barrel does 1,700 kWh of work at 100% efficiency.' },
    { q: 'Fuel burned by a Boeing 747 in an hour', v: 12e3, unit: 'litres', hint: 'About 10 tonnes; 4 litres a second.' },
    { q: 'Proven oil reserves worldwide', v: 1.7e12, unit: 'barrels', hint: 'Fifty years at today’s 100M barrels a day.' },
    { q: 'Gold ever mined', v: 215e3, unit: 'tonnes', hint: 'A cube 22 metres on a side.' },
    { q: 'Steel produced worldwide in a year', v: 1.9e9, unit: 'tonnes', hint: 'Over half of it in China.' },
    { q: 'Cement produced worldwide in a year', v: 4.1e9, unit: 'tonnes', hint: '~8% of global CO2.' },
    { q: 'Plastic produced worldwide in a year', v: 400e6, unit: 'tonnes', hint: 'About 50 kg per person.' },
    { q: 'Wheat harvested worldwide in a year', v: 800e6, unit: 'tonnes', hint: '~100 kg per person; rice is similar.' },
    { q: 'Bananas eaten worldwide in a year', v: 100e9, unit: 'bananas', hint: 'Roughly 12 per person.' },
    { q: 'Cups of tea drunk in the UK in a day', v: 100e6, unit: 'cups', hint: '1.5 per person per day.' },
    { q: 'Pints of beer sold in UK pubs in a year', v: 4e9, unit: 'pints', hint: '~45,000 pubs at ~250 a day.' },
    { q: 'Bottles of wine produced worldwide in a year', v: 32e9, unit: 'bottles', hint: '240M hectolitres; France, Italy and Spain make half.' },
    { q: 'Big Macs sold worldwide in a day', v: 6e6, unit: 'burgers', hint: '~2.2bn a year across 43,000 restaurants.' },

    /* Technology and the internet */
    { q: 'Internet users worldwide', v: 5.5e9, unit: 'users', hint: 'Two thirds of humanity.' },
    { q: 'Smartphones in use worldwide', v: 7e9, unit: 'phones', hint: 'Roughly one per adult; many people have two.' },
    { q: 'Emails sent worldwide in a day', v: 360e9, unit: 'emails', hint: 'Most of it automated or spam.' },
    { q: 'YouTube video uploaded every minute', v: 500, unit: 'hours', hint: '~30,000 hours an hour.' },
    { q: 'Videos watched on TikTok in a day', v: 1e9, unit: 'hours', hint: '~1.5bn users at ~50 minutes.' },
    { q: 'Wikipedia articles in English', v: 7e6, unit: 'articles', hint: '~65M across all languages.' },
    { q: 'Transistors on a modern phone processor', v: 20e9, unit: 'transistors', hint: 'Apple’s A-series chips are 15-20bn.' },
    { q: 'Data created worldwide in a year', v: 150e21, unit: 'bytes', hint: '~150 zettabytes; most is never stored.' },
    { q: 'Bitcoin transactions in a day', v: 500e3, unit: 'transactions', hint: 'Seven a second; Visa does ~2,000 a second.' },
    { q: 'Visa transactions in a day', v: 750e6, unit: 'transactions', hint: '~275bn a year.' },
    { q: 'Apps in the Apple App Store', v: 1.9e6, unit: 'apps', hint: 'Google Play has ~2.5M.' },
    { q: 'Active satellites orbiting Earth', v: 10e3, unit: 'satellites', hint: 'Starlink is more than half of them.' },
    { q: 'Lines of code in the Linux kernel', v: 30e6, unit: 'lines', hint: 'Grown by ~1M a year for three decades.' },
    { q: 'Employees at Google (Alphabet)', v: 180e3, unit: 'employees', hint: 'Microsoft and Apple are similar; Amazon is 1.5M.' },
    { q: 'Employees at Walmart worldwide', v: 2.1e6, unit: 'employees', hint: 'The largest private employer on Earth.' },
    { q: 'Employees at the Indian Railways', v: 1.2e6, unit: 'employees', hint: 'One of the largest employers of any kind.' },

    /* Money and markets */
    { q: 'World GDP in a year', v: 105e12, unit: 'USD', hint: '~$13,000 per person.' },
    { q: 'GDP of the United States in a year', v: 28e12, unit: 'USD', hint: 'A quarter of the world; ~$85,000 per person.' },
    { q: 'GDP of the Netherlands in a year', v: 1.1e12, unit: 'USD', hint: '~$60,000 per person, among the richest large economies.' },
    { q: 'GDP of the United Kingdom in a year', v: 3.4e12, unit: 'USD', hint: 'Sixth in the world; ~$50,000 per person.' },
    { q: 'Total value of the world’s stock markets', v: 110e12, unit: 'USD', hint: 'About equal to a year of world GDP; the US is roughly half.' },
    { q: 'Market capitalisation of the AEX index', v: 1.1e12, unit: 'EUR', hint: 'ASML alone is a third of it.' },
    { q: 'Market capitalisation of Apple', v: 3.3e12, unit: 'USD', hint: 'Three times Dutch GDP.' },
    { q: 'Foreign exchange traded worldwide in a day', v: 7.5e12, unit: 'USD', hint: 'Every week the FX market turns over a year of world GDP.' },
    { q: 'US Treasury debt outstanding', v: 35e12, unit: 'USD', hint: 'About 120% of US GDP.' },
    { q: 'Total money in the world (broad money, M2)', v: 120e12, unit: 'USD', hint: 'Physical cash is only ~$8tn of it.' },
    { q: 'Physical banknotes and coins in the world', v: 8e12, unit: 'USD', hint: 'Roughly $1,000 per person.' },
    { q: 'Shares traded on the New York Stock Exchange in a day', v: 4e9, unit: 'shares', hint: 'US-wide across all venues is ~11bn.' },
    { q: 'Shares traded across all US exchanges in a day', v: 11e9, unit: 'shares', hint: 'Spread across 16 exchanges and the dark pools.' },
    { q: 'Options contracts traded in the US in a day', v: 45e6, unit: 'contracts', hint: 'Over 10bn a year, doubled since 2019.' },
    { q: 'Trading days in a year', v: 252, unit: 'days', hint: '365 minus weekends minus ~9 holidays.' },
    { q: 'Seconds in a US equity trading day', v: 23400, unit: 'seconds', hint: '6.5 hours, 9:30 to 16:00.' },
    { q: 'Assets managed by BlackRock', v: 11e12, unit: 'USD', hint: 'The largest asset manager; Vanguard is ~9tn.' },
    { q: 'Employees at Goldman Sachs', v: 46e3, unit: 'employees', hint: 'JPMorgan is ~300k.' },
    { q: 'Employees at JPMorgan Chase', v: 300e3, unit: 'employees', hint: 'The largest bank by market value.' },
    { q: 'Hedge funds in the world', v: 15e3, unit: 'funds', hint: 'Managing ~$4.5tn between them.' },
    { q: 'Price of an ounce of gold', v: 2500, unit: 'USD', hint: 'Moves; check the morning of. A tonne is 32,150 ounces.' },
    { q: 'Cost of a Boeing 737 MAX', v: 120e6, unit: 'USD', hint: 'List price; airlines pay half that.' },
    { q: 'Cost of the Channel Tunnel', v: 4.65e9, unit: 'GBP', hint: 'In 1994 money; about GBP 12bn today.' },
    { q: 'Annual budget of the NHS', v: 190e9, unit: 'GBP', hint: 'About GBP 2,800 per person.' },
    { q: 'Amazon revenue in a year', v: 640e9, unit: 'USD', hint: 'Walmart is ~$680bn, the largest company by sales.' },
    { q: 'Transfer fee record in football', v: 222e6, unit: 'EUR', hint: 'Neymar, 2017.' },
    { q: 'Prize money for winning Wimbledon singles', v: 3e6, unit: 'GBP', hint: 'GBP 3M in 2025 out of a GBP 53M pot.' },

    /* The human body and everyday life */
    { q: 'Breaths taken by a person in a day', v: 20e3, unit: 'breaths', hint: '~14 a minute.' },
    { q: 'Blood pumped by the heart in a day', v: 7000, unit: 'litres', hint: '~5 litres a minute.' },
    { q: 'Neurons in the human brain', v: 86e9, unit: 'neurons', hint: 'Ten times the number of people alive.' },
    { q: 'Bacteria in the human gut', v: 4e13, unit: 'bacteria', hint: 'About equal to the number of human cells.' },
    { q: 'Bones in the adult human body', v: 206, unit: 'bones', hint: 'A baby has ~270, which fuse.' },
    { q: 'Steps walked by an average person in a day', v: 5000, unit: 'steps', hint: 'About 4 km; the 10,000 target is marketing.' },
    { q: 'Kilometres walked in an 80-year life', v: 120e3, unit: 'km', hint: '4 km a day for 80 years: three times round the world.' },
    { q: 'Calories eaten by a person in a year', v: 900e3, unit: 'kcal', hint: '~2,500 a day.' },
    { q: 'Water drunk by a person in a lifetime', v: 60e3, unit: 'litres', hint: '2 litres a day for 80 years.' },
    { q: 'Hours a person sleeps in a lifetime', v: 230e3, unit: 'hours', hint: 'A third of 80 years: ~26 years asleep.' },
    { q: 'Words spoken by a person in a day', v: 16e3, unit: 'words', hint: 'Roughly the same for men and women.' },
    { q: 'Words in a typical novel', v: 90e3, unit: 'words', hint: 'A 300-page paperback.' },
    { q: 'Words read by a fast reader in an hour', v: 18e3, unit: 'words', hint: '300 words a minute.' },
    { q: 'Blinks in a day', v: 15e3, unit: 'blinks', hint: '~15 a minute while awake.' },
    { q: 'Hairs shed from a head in a day', v: 80, unit: 'hairs', hint: 'Out of ~100,000.' },
    { q: 'Cells that die and are replaced in your body each day', v: 330e9, unit: 'cells', hint: 'About 1% of the body’s 37 trillion.' },
    { q: 'Length of DNA in one human cell, uncoiled', v: 2, unit: 'metres', hint: '3 billion base pairs at 0.34 nm each; all your cells together reach the Sun and back many times.' },
    { q: 'Sheets of paper in a tree', v: 8000, unit: 'sheets', hint: 'A 40-foot pine gives ~16 reams.' },
    { q: 'Weight of the air in a large living room', v: 60, unit: 'kg', hint: '50 m3 at 1.2 kg/m3.' },
    { q: 'Volume of a human body', v: 70, unit: 'litres', hint: 'We are roughly the density of water.' },
    { q: 'Weddings in the UK in a year', v: 250e3, unit: 'weddings', hint: 'About 4 per 1,000 people.' },
    { q: 'Babies born in the UK in a day', v: 1650, unit: 'births', hint: '~600,000 a year; deaths are similar.' },
    { q: 'Marathon runners finishing the London Marathon', v: 53e3, unit: 'finishers', hint: 'The record field in 2024.' },
    { q: 'Golf balls lost in the United States in a year', v: 300e6, unit: 'balls', hint: '~25M golfers, a dozen each.' },
    { q: 'Christmas trees sold in the UK in a year', v: 8e6, unit: 'trees', hint: 'Roughly one household in three.' },
    { q: 'Letters delivered by Royal Mail in a day', v: 20e6, unit: 'letters', hint: 'Down from 80M a day in 2005.' },
    { q: 'Parcels delivered in the UK in a day', v: 14e6, unit: 'parcels', hint: '~5bn a year, half of them from Amazon-scale senders.' },
    { q: 'Petrol stations in the United Kingdom', v: 8300, unit: 'stations', hint: 'Falling; one per 8,000 people.' },
    { q: 'Supermarkets in the United Kingdom', v: 15e3, unit: 'stores', hint: 'Tesco alone has ~2,800 UK stores.' },
    { q: 'Hospitals in the United Kingdom', v: 1900, unit: 'hospitals', hint: 'NHS acute hospitals are ~200 of them; the rest are community and private.' },
    { q: 'Doctors in the United Kingdom', v: 330e3, unit: 'doctors', hint: 'About one per 200 people.' },
    { q: 'Schools in the United Kingdom', v: 32e3, unit: 'schools', hint: '~24,000 in England.' },
    { q: 'Churches in England', v: 40e3, unit: 'churches', hint: '16,000 of them Church of England.' },
    { q: 'Trains run by Network Rail in a day', v: 20e3, unit: 'trains', hint: 'On 16,000 km of track.' },
    { q: 'Traffic lights in London', v: 6e3, unit: 'junctions', hint: 'Signalled junctions; ~60,000 individual lamps.' },
    { q: 'Street lights in the United Kingdom', v: 7e6, unit: 'lamps', hint: 'One per ten people.' },
    { q: 'Lifts (elevators) in the world', v: 20e6, unit: 'lifts', hint: 'They carry ~1bn people a day.' },
    { q: 'Piano keys', v: 88, unit: 'keys', hint: '52 white, 36 black.' },
    { q: 'Squares on a Go board', v: 361, unit: 'points', hint: '19 x 19 intersections.' },
    { q: 'Possible positions in chess', v: 1e44, unit: 'positions', hint: 'The Shannon number for games is 10^120.' },
    { q: 'Ways to arrange a Rubik’s cube', v: 4.3e19, unit: 'arrangements', hint: '43 quintillion; any of them solvable in 20 moves.' },
    { q: 'Grains of sand on all the world’s beaches', v: 7.5e18, unit: 'grains', hint: 'Fewer than the stars in the observable universe (~10^22).' },
    { q: 'Raindrops in a millimetre of rain over a football pitch', v: 1e9, unit: 'drops', hint: '7,000 m2 x 1 mm = 7 m3, at ~7 mm3 a drop... about a billion.' },
    { q: 'Snowflakes in a cubic metre of fresh snow', v: 1e8, unit: 'flakes', hint: 'Hundreds of thousands per litre.' },
  ];


  /* ---------------- reported bank ----------------
   * Quantities that were actually put to candidates, per the scrape: Glassdoor,
   * Wall Street Oasis, prep-site compilations and the classic published lists.
   * tier 1 = IMC with an Amsterdam or European report, 2 = IMC elsewhere or
   * office unknown, 3 = another firm or a published list.
   *
   * type 'fermi'   one quantity; `variants` means a fresh one each time it recurs
   * type 'town'    the reported "dentists x schools in a village" shape: a product
   *                of two counts in a town, with both inputs asked for first
   * type 'noisy'   the market has a computable FAIR but settles on a realised
   *                draw, so accuracy is graded against fair and P&L against the draw
   * type 'odds'    an event contract paying 100; fair comes from de-vigging the odds
   */
  const REPORTED = [
    { id: 'cats-japan', tier: 1, type: 'fermi', src: 'IMC, Glassdoor, Amsterdam. Asked twice, once as "what is the bid and ask?"',
      q: 'Cats in Japan', v: 9.1e6, unit: 'cats',
      hint: '125M people and about 55M households. Roughly one household in ten keeps a cat, 1.7 cats each. The pet-food industry survey puts it near 9 million, a little ahead of dogs.' },
    { id: 'country-pop', tier: 1, type: 'fermi', src: 'IMC, Glassdoor, phone screen, United Kingdom: "make a market for the population of a country"',
      variants: [
        { q: 'Population of Canada', v: 41e6, unit: 'people', hint: 'A little over a tenth of the United States.' },
        { q: 'Population of Japan', v: 124e6, unit: 'people', hint: 'Falling by more than half a million a year.' },
        { q: 'Population of Brazil', v: 212e6, unit: 'people', hint: 'Half of South America.' },
        { q: 'Population of Spain', v: 49e6, unit: 'people', hint: 'Between Poland and Italy.' },
        { q: 'Population of Poland', v: 37e6, unit: 'people', hint: 'The fifth largest in the EU.' },
        { q: 'Population of South Korea', v: 52e6, unit: 'people', hint: 'Half of it in greater Seoul.' },
        { q: 'Population of Indonesia', v: 283e6, unit: 'people', hint: 'Fourth largest in the world.' },
        { q: 'Population of Egypt', v: 116e6, unit: 'people', hint: 'Nearly all of it along the Nile.' },
        { q: 'Population of Argentina', v: 46e6, unit: 'people', hint: 'A third of it in greater Buenos Aires.' },
        { q: 'Population of Sweden', v: 10.6e6, unit: 'people', hint: 'The largest Nordic country, about twice Denmark.' },
        { q: 'Population of Belgium', v: 11.8e6, unit: 'people', hint: 'Two thirds of the Netherlands.' },
        { q: 'Population of Italy', v: 59e6, unit: 'people', hint: 'Shrinking; a touch under France and the UK.' },
        { q: 'Population of France', v: 68e6, unit: 'people', hint: 'Level with the UK.' },
        { q: 'Population of the United Kingdom', v: 69e6, unit: 'people', hint: 'England alone is 57M.' },
        { q: 'Population of Mexico', v: 130e6, unit: 'people', hint: 'Tenth largest in the world.' },
        { q: 'Population of Turkey', v: 86e6, unit: 'people', hint: 'Level with Germany.' },
        { q: 'Population of South Africa', v: 63e6, unit: 'people', hint: 'A little under the UK.' },
        { q: 'Population of Ireland', v: 5.4e6, unit: 'people', hint: 'The Republic; the island is about 7.3M.' },
        { q: 'Population of Switzerland', v: 9.0e6, unit: 'people', hint: 'Half the Netherlands.' },
        { q: 'Population of Portugal', v: 10.6e6, unit: 'people', hint: 'Level with Sweden and Greece.' },
        { q: 'Population of Australia', v: 27e6, unit: 'people', hint: 'Fewer than the Netherlands plus Belgium, on a continent.' },
        { q: 'Population of the Netherlands', v: 18.0e6, unit: 'people', hint: 'Know this one exactly for an Amsterdam interview.' },
      ] },
    { id: 'town-product', tier: 2, type: 'town', src: 'IMC, later rounds: "dentists in a village times schools in that village", spread within 10% of bid, one minute then ten seconds' },
    { id: 'top3-of-5-dice', tier: 2, type: 'noisy', src: 'IMC, later rounds, same clock and spread rule',
      q: 'The sum of the largest three of five fair dice', unit: 'pips', fair: 34811 / 2592, draw: 'top3of5',
      hint: 'Fair is 13.43 exactly. Reason from order statistics: five dice sum to 17.5, and the two smallest of five average about 1.5 and 2.6, so 17.5 minus 4.1. It settles on an actual roll, so you can quote well and still lose.' },
    { id: 'urn-red', tier: 2, type: 'noisy', src: 'IMC, reported online: "I will pay you one pound per red marble. Make me a market."',
      q: 'Red marbles in an urn of 100, red and blue in unknown proportion, paid at one pound each', unit: 'pounds', fair: 50, draw: 'urn100',
      hint: 'With no information the fair is 50 and the uncertainty is enormous, so the honest market is wide. The test is whether you say why it is wide and what a sample of marbles would do to it.' },
    { id: 'event-odds', tier: 2, type: 'odds', src: 'IMC, final round: "predict a tennis match and make a market on it"; and later rounds: betting against a prior with a bookmaker quoting' },
    { id: 'everest-sea', tier: 2, type: 'fermi', src: 'IMC, reported online',
      q: 'Rise in global sea level if the mass of Mount Everest were sunk in the ocean', v: 0.17, unit: 'millimetres',
      hint: 'The circulated mass is about 1.6e14 kg; at 2,700 kg per cubic metre that is 6e10 cubic metres. Spread over 3.6e14 square metres of ocean it is 0.17 mm. A generous cone for the mountain gets you nearer 0.7 mm, so anything from 0.1 to 1 is defensible if you show the division.' },
    { id: 'digits-100-factorial', tier: 2, type: 'fermi', src: 'IMC on Reddit and QuantProf; also tagged at SIG and Optiver',
      q: 'Digits in 100 factorial', v: 158, unit: 'digits',
      hint: 'Sum of log10 k for k to 100, or Stirling: 100 log10(100/e) plus about 1.4 is 157.97, so 158 digits.' },
    { id: 'us-olympic-golds', tier: 3, type: 'fermi', src: 'Old Mission, final round and phone screen, with P&L and exposure tracked across iterations',
      q: 'Olympic gold medals won by the United States, all Games through Paris 2024', v: 1219, unit: 'gold medals',
      hint: 'About 1,105 at Summer Games and 114 at Winter Games. Thirty Summer Games at roughly 37 each is the quick route.' },
    { id: 'aaa-batteries-uk', tier: 3, type: 'fermi', src: 'SIG, reported online',
      q: 'AAA batteries sold in the United Kingdom in a year', v: 200e6, unit: 'batteries',
      hint: 'The UK buys about 600 million household batteries a year, roughly nine a person. AA is the largest share and AAA about a third.' },
    { id: 'three-dice-sum', tier: 3, type: 'noisy', src: 'SIG, reported online: "I will pay you the sum of three dice. What would you pay, and where would you sell?"',
      q: 'The sum of three fair dice', unit: 'pips', fair: 10.5, draw: 'sum3',
      hint: 'Fair is 10.5 with a standard deviation of 2.96. Buy below, sell above, and the gap between the two is what you charge for the variance.' },
    { id: 'gas-stations-us', tier: 3, type: 'fermi', src: 'Published interview lists, reported online',
      q: 'Petrol stations in the United States', v: 145e3, unit: 'stations',
      hint: '340M people and 285M vehicles. One station per 2,000 vehicles or so.' },
    { id: 'pizzas-us-day', tier: 3, type: 'fermi', src: 'Published interview lists, reported online',
      q: 'Pizzas eaten in the United States in a day', v: 8.2e6, unit: 'pizzas',
      hint: 'About three billion a year, nine a person, so a little over eight million a day.' },
    { id: 'cars-stolen-us-month', tier: 3, type: 'fermi', src: 'Published interview lists, reported online',
      q: 'Cars stolen in the United States in a month', v: 85e3, unit: 'cars',
      hint: 'About a million a year recently, one vehicle in 280.' },
    { id: 'yankees-season', tier: 3, type: 'fermi', src: 'Published interview lists, reported online',
      q: 'Total attendance at New York Yankees home games in a season', v: 3.3e6, unit: 'people',
      hint: '81 home games at about 41,000 each.' },
    { id: 'wall-street-jobs', tier: 3, type: 'fermi', src: 'Published interview lists, reported online',
      q: 'People employed in the securities industry in New York City', v: 200e3, unit: 'people',
      hint: 'The state comptroller counts just under 200,000, about one New York job in twenty.' },
    { id: 'ocean-drops', tier: 3, type: 'fermi', sprintOnly: true, src: 'Published interview lists, reported online',
      q: 'Drops of water in the oceans', v: 2.7e25, unit: 'drops',
      hint: 'Ocean volume is 1.3 billion cubic kilometres, which is 1.3e24 millilitres, at twenty drops a millilitre.' },
  ];

  /* People per establishment, United Kingdom, rounded. Used to build town products. */
  const TOWN_RATES = [
    { key: 'dentists', label: 'Dentists', per: 1900 },
    { key: 'schools', label: 'Schools', per: 2750 },
    { key: 'pubs', label: 'Pubs', per: 1500 },
    { key: 'gps', label: 'GPs', per: 1800 },
    { key: 'pharmacies', label: 'Pharmacies', per: 5000 },
    { key: 'hairdressers', label: 'Hairdressers and barbers', per: 1400 },
    { key: 'churches', label: 'Churches', per: 1700 },
    { key: 'postoffices', label: 'Post offices', per: 5800 },
  ];
  const TOWN_SIZES = [5000, 12000, 30000, 80000];

  /* Bookmaker decimal odds for a two-player match: favourite, outsider. */
  const ODDS_PAIRS = [[1.40, 3.10], [1.25, 4.20], [1.62, 2.40], [1.85, 2.05], [1.12, 7.00], [1.50, 2.75], [2.10, 1.80]];

  /* ---------------- judgement bank: the interruptions, as multiple choice ----------------
   * `why` is the model answer, read aloud in the debrief.
   */
  const JUDGEMENT = [
    {
      q: 'You quote 55 at 67. I buy. You requote, I buy again. I buy a third time. What do you do?',
      opts: [
        'Keep the same market. My estimate has not changed, so my price should not.',
        'Move both prices up, widen, and show less size. Persistent one-way flow is information.',
        'Move both prices up but tighten, to win more of the flow.',
        'Stop quoting and ask what they know.',
      ],
      a: 1,
      why: 'Each fill is evidence your fair is too low, and your short is growing. So you march the price with the flow, widen because the counterparty looks informed, and cut the size you show. Refusing to quote at all is a worse answer than a wide quote.',
    },
    {
      q: 'One of the two traders keeps buying from you and the other keeps selling. What does that change?',
      opts: [
        'Nothing. Each trade is independent.',
        'Widen: two active counterparties means twice the adverse selection.',
        'Tighten. You are capturing the spread with little net inventory, so more flow is pure profit.',
        'Quote only to the seller.',
      ],
      a: 2,
      why: 'Two-sided flow is the market maker’s dream: you earn the spread and your net position barely moves. One-sided flow from an informed room is the dangerous case. Distinguishing the two out loud is the strongest single line available in this exercise.',
    },
    {
      q: 'You are short ten lots and your fair is 61. How should your market look?',
      opts: [
        'Symmetric around 61, just wider: 52 at 70.',
        'Skewed up: lift the bid toward fair and push the offer away, say 60 at 68, with more size on the bid.',
        'Skewed down, to attract buyers who will take you out.',
        'Pull the market entirely until you are flat.',
      ],
      a: 1,
      why: 'Skew, do not merely widen. You want to be hit on the bid and paid richly if you get shorter still. And be willing to pay through your own fair to flatten: a small certain loss beats an uncertain large one.',
    },
    {
      q: '"Would you show that price in ten times the size?"',
      opts: [
        'Yes, the same price. My fair has not changed.',
        'No, I would not trade at all in that size.',
        'Wider, or the normal price for one clip and the rest worked in pieces.',
        'Tighter, because large trades are usually uninformed.',
      ],
      a: 2,
      why: 'Three reasons to widen, and naming all three is the full-marks answer: adverse selection rises with size, inventory risk scales directly, and a large position costs more to unwind. Never simply refuse.',
    },
    {
      q: 'You learn the counterparty can see the true value. What is the right strategy?',
      opts: [
        'Quote very wide so they cannot profit.',
        'Follow their trades: each one tells you which side you are wrong on, and stop when they stop.',
        'Quote randomly so they cannot read you.',
        'Refuse to quote.',
      ],
      a: 1,
      why: 'Against a fully informed counterparty your quote is a measuring instrument. Chase every trade in the direction they hit you, and treat the moment they stop trading as the signal that you have arrived at fair.',
    },
    {
      q: 'You have quoted markets on city A’s population, city B’s density, and the product. What must be true?',
      opts: [
        'Nothing. They are separate estimates.',
        'Only that each bid is below each ask.',
        'The product of your component mid-prices must sit inside your product market, or the three quotes are arbitrageable against each other.',
        'They must all have the same percentage spread.',
      ],
      a: 2,
      why: 'Every fair value in the room must descend from one set of underlying estimates. Re-estimating a quantity independently is how you write someone else a free option against your own book.',
    },
    {
      q: 'Your fair is 61 and news arrives that city A’s population is 20% higher than you assumed. New fair?',
      opts: [
        'About 73, because the value is a product so a proportional move in an input is proportional in the output.',
        'About 66, because one of three inputs moved.',
        'About 81, because uncertainty compounds.',
        'Unchanged until I see the other inputs.',
      ],
      a: 0,
      why: 'A pure product transmits proportional changes one for one. Say that in those words, recentre, and tighten, because the news also removed uncertainty from that leg.',
    },
    {
      q: 'They ask for a contract paying 100 if the quantity exceeds a level far above your fair. What do you quote?',
      opts: [
        '0 bid at 0 offer, since it cannot happen.',
        '0 bid at a small offer, wide, because a far strike is a bet on my uncertainty rather than on my fair.',
        '50 at 55, since I cannot rule it out.',
        'The same spread I use on the underlying.',
      ],
      a: 1,
      why: 'A digital struck near your fair is a bet on your fair; struck far away it is a bet on the tails of your error distribution, which you know far less well. So widen in the wings, and never quote a zero offer: you are selling insurance against your own model being wrong.',
    },
    {
      q: 'The quantity you are quoting suddenly moves 5% and you do not know why. What do you do first?',
      opts: [
        'Recentre immediately on the new level.',
        'Ignore it and hold your fair.',
        'Ask whether it is signal or noise: volume, breadth, news, depth, persistence.',
        'Widen to the maximum and stop trading.',
      ],
      a: 2,
      why: 'Signal means recentre fast. Noise means hold your fair, widen, and let the mean reversion pay you. The graded content is that you asked the question rather than reflexively doing either.',
    },
    {
      q: '"What is your worst-case loss on your current position?"',
      opts: [
        'Unbounded, since the quantity has no ceiling.',
        'Lots times the difference between a stated plausible extreme and my average entry, with the dominant risk named.',
        'My total capital.',
        'The spread I quoted, times the number of lots.',
      ],
      a: 1,
      why: 'Turn a vague question into a number, a method and an identified dominant risk. On a compound city market the real risk is usually definitional, not statistical: if "population" meant the metropolitan area all along, your fair jumps before any randomness is involved.',
    },
    {
      q: 'Another trader in the room starts quoting a market that overlaps yours: their bid is above your ask.',
      opts: [
        'Match their market immediately.',
        'Sell to them at their bid if it is above my fair, and ask myself what they might know that I do not.',
        'Widen so I am never crossed.',
        'Ignore it, my fair is my fair.',
      ],
      a: 1,
      why: 'A crossed market is either free money or information. Take the trade if it beats your fair, and simultaneously update on the possibility that their fair is better than yours. Doing both at once is the answer.',
    },
    {
      q: 'Why is your spread the width it is?',
      opts: [
        'It is a convention: about 10% of the price.',
        'Because of the uncertainty in my fair, the chance the counterparty is informed, the size, my inventory, and the competition.',
        'To make sure I make money on every trade.',
        'Because a narrow spread looks confident.',
      ],
      a: 1,
      why: 'A spread that you can decompose into named inputs is a derived number. A spread you cannot justify is an arbitrary one, and they will find out which it is by asking exactly this.',
    },
    {
      q: 'You quoted 55 at 67 and the true value settles at 63. You sold two lots at 67 and bought one at 55. What is your P&L?',
      opts: ['+16', '+12', '+8', '-4'],
      a: 0,
      why: 'Sold two at 67 against 63 is +4 each, so +8. Bought one at 55 against 63 is +8. Total +16. Say the position first, then the number: short one lot net, and plus sixteen.',
    },
    {
      q: 'Halfway through, you realise your opening fair was wrong by a factor of two. What do you say?',
      opts: [
        'Nothing, and drift the price gradually so it is not obvious.',
        'Name the error, give the corrected fair and the corrected market, and re-mark the existing position.',
        'Defend the original number, since changing your mind looks weak.',
        'Ask to start the exercise again.',
      ],
      a: 1,
      why: 'How you react to being wrong is explicitly what this round assesses. Concede fast, say what the error was, restate the number, and re-mark. Drifting quietly is the worst of the four because it reads as hiding it.',
    },
    {
      q: 'They challenge an answer you are confident is correct: "Are you sure? That does not seem right."',
      opts: [
        'Change the answer; they are the trader.',
        'Re-derive it in one line and hold, changing only if they give an actual argument.',
        'Say you are not sure and offer a range.',
        'Ask them what the right answer is.',
      ],
      a: 1,
      why: 'IMC challenges correct answers deliberately. A candidate in the reported set was rejected with everything correct, for hedging. Re-derive briefly, hold, and if you do fold, say precisely what changed your mind.',
    },
  ];

  return { CITIES, FERMI, REPORTED, TOWN_RATES, TOWN_SIZES, ODDS_PAIRS, JUDGEMENT, greatCircle, density };
})();
